### ISSUE TITLE
refresh START or WAYFIRE left bottom menu when /usr/share/applications changes

### ISSUE THREAD

**Issue by hiIexistlol** [WayfireWM/wf-shell#92] opened 2021-06-12 14:02 UTC
Please describe what you want Wayfire to do.
^
If applicable, give an example: User does X, Y, Wayfire does Z
^

when i download something and want to start it multiple times easy without nohup files or console windows everywhere
the menu is nice, but I have to logout first, which is not so good,
please add this!

**Comment by ammen99** [comment] 2021-06-12 14:40
Actually a duplicate of #34. For a quick workaround, you can kill wf-panel and start it again. Would probably make sense to bind this to a keybinding for ease of use.

**Closed by ammen99** 2021-06-12 14:40 UTC

**Comment by hiIexistlol** [comment] 2021-06-12 14:52
alrighty

**Comment by soreau** [comment] 2021-06-12 15:12
> Would probably make sense to bind this to a keybinding for ease of use.
👎

It needs inotify handler hooked up to each directory so it reloads when files in the directory change.

**Comment by ammen99** [comment] 2021-06-12 15:38
> > Would probably make sense to bind this to a keybinding for ease of use.
> > 👎
> 
> It needs inotify handler hooked up to each directory so it reloads when files in the directory change.

Nah, there are multiple directories. I don't plan to reimplement the xdg specification.

**Comment by soreau** [comment] 2021-06-12 15:41
> > > Would probably make sense to bind this to a keybinding for ease of use.
> > > -1
> > 
> > 
> > It needs inotify handler hooked up to each directory so it reloads when files in the directory change.
> 
> Nah, there are multiple directories. I don't plan to reimplement the xdg specification.

This has nothing to do with implementing XDG, it has everything to do with fixing the bug properly.

**Comment by wb9688** [comment] 2021-06-14 09:52
You could use [GAppInfoMonitor](https://developer.gnome.org/gio/stable/GAppInfoMonitor.html)
