### ISSUE TITLE
window-list: show only current virtual desktop applications

### ISSUE THREAD

**Issue by birdie-github** [WayfireWM/wf-shell#194] opened 2023-10-16 10:19 UTC
Pardon me but I don't understand how to make window-list only show applications for the current virtual desktop. It shows applications for all virtual desktops.

I'm using WayFire 0.8.

**Comment by NamorNiradnug** [comment] 2023-10-16 10:21
Probably duplicate of #120

**Comment by ammen99** [comment] 2023-10-16 10:42
Yes, definitely a duplicate

**Closed by ammen99** 2023-10-16 10:42 UTC
