### ISSUE TITLE
Breaking ABI change

### ISSUE THREAD

**Issue by mamins1376** [WayfireWM/wf-shell#50] opened 2020-04-03 19:38 UTC
Installing on Void, a linking error happens (issue https://github.com/void-linux/void-packages/issues/20618).
```
$ wf-background
wf-background: symbol lookup error: wf-background: undefined symbol: _ZN12wf_animation6circleE
```

According to @xtraeme, https://github.com/WayfireWM/wf-config/commit/211a86c35419871ca8d47c3d50d128a326e9d084 caused that.

```
$ ldd -r `which wf-background`
...
undefined symbol: _ZN12wf_animation6circleE	(/sbin/wf-background)
undefined symbol: _ZN12wf_animation6linearE	(/sbin/wf-background)
undefined symbol: _ZN11wf_duration7runningEv	(/sbin/wf-background)
undefined symbol: _ZN11wf_durationC1ESt10shared_ptrI11wf_option_tESt8functionIFddEE	(/sbin/wf-background)
undefined symbol: _ZN11wf_option_t19rem_updated_handlerEPSt8functionIFvvEE	(/sbin/wf-background)
undefined symbol: _ZN14wayfire_config13reload_configEv	(/sbin/wf-background)
undefined symbol: _ZN11wf_option_t9as_stringB5cxx11Ev	(/sbin/wf-background)
undefined symbol: _ZNK11wf_duration8progressEv	(/sbin/wf-background)
undefined symbol: _ZN22wayfire_config_section10get_optionENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES5_	(/sbin/wf-background)
undefined symbol: _Z17new_static_optionNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(/sbin/wf-background)
undefined symbol: _ZN11wf_option_t19add_updated_handlerEPSt8functionIFvvEE	(/sbin/wf-background)
undefined symbol: _ZN11wf_duration5startEdd	(/sbin/wf-background)
undefined symbol: _ZN14wayfire_config11get_sectionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(/sbin/wf-background)
undefined symbol: _ZN11wf_option_t6as_intEv	(/sbin/wf-background)
undefined symbol: _ZN14wayfire_configC1ENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE	(/sbin/wf-background)
```

**Comment by ammen99** [comment] 2020-04-03 19:39
You just need to update wf-config. We require version 0.4 with latest wf-shell.

**Comment by xtraeme** [comment] 2020-04-03 19:40
@ammen99 the issue is that we've updated wf-config to 0.4.0, but wf-shell is still 0.3.

**Comment by xtraeme** [comment] 2020-04-03 19:41
@ammen99 you could have fixed this just by bumping SONAME of wf-config. This would have been enough for us to detect the API/ABI incompatibility.

**Comment by ammen99** [comment] 2020-04-03 19:44
I don't think wf-config uses a .so name, plus meson.build clearly says it requires wf-config >= 0.4 

That being said, soname would be a good idea, but this is an issue in wf-config, not wf-shell (please open an issur there). Closing this one.

**Closed by ammen99** 2020-04-03 19:44 UTC

**Comment by xtraeme** [comment] 2020-04-03 19:46
```
[juan@leysa ~]$ objdump -p /usr/lib/libwf-config.so.0|grep -i soname
  SONAME               libwf-config.so.0
[juan@leysa ~]$
```
